// document-classification.ts
// Types and interfaces matching the database schema.
// Pure data definitions — no logic, no I/O, no dependencies.
// Every other file imports from here.

// Types for external dependencies — using structural typing to avoid importing heavy packages
// This prevents Vitest from loading the full openai/supabase packages during testing

// =============================================================================
// Constrained types — match CHECK constraints in the documents table
// If you add a value here, you must also add it to the database CHECK constraint
// =============================================================================

export type Domain = 'system' | 'persona' | 'workspace' | 'project' | 'general';
export type Protection = 'open' | 'guarded' | 'protected' | 'immutable';
export type OwnerType = 'system' | 'user' | 'team';
export type DocumentStatus = 'idea' | 'planning' | 'active' | 'done';
export type SourceType = 'text' | 'pdf' | 'docx' | 'spreadsheet' | 'code' | 'image' | 'audio' | 'video' | 'web' | 'email' | 'slides' | 'handwriting';

// Chunk metadata types — stored on document_chunks table
export type ChunkStrategy = 'header' | 'paragraph' | 'sentence' | 'semantic' | 'forced';
export type ChunkContentType = 'text' | 'image_description' | 'table_extraction' | 'code_block' | 'transcript' | 'slide_text';

// =============================================================================
// Document interfaces — match the documents table columns
// =============================================================================

// Full document row — what you get back from a SELECT * on documents
export interface IDocumentProps {
  id: number;
  name: string;
  domain: Domain;
  document_type: string;
  project: string | null;
  protection: Protection;
  owner_type: OwnerType;
  owner_id: string | null;
  is_auto_load: boolean;
  content: string;
  description: string | null;
  content_hash: string | null;
  // search_vector is generated by Postgres — never read/write from TypeScript
  file_path: string | null;
  file_permissions: string | null;
  source_type: SourceType;
  source_url: string | null;
  agent: string | null;
  status: DocumentStatus | null;
  skill_ref: string | null;
  embedding_model_id: string | null;
  schema_version: number;
  content_length: number;      // generated by Postgres from content
  chunk_count: number;
  retrieval_count: number;
  deleted_at: string | null;
  created_at: string;
  updated_at: string;
}

// What you pass to create a new document
// Required: name, domain, document_type, content
// Everything else has database defaults or is optional
export interface ICreateDocumentProps {
  name: string;
  domain: Domain;
  document_type: string;
  content: string;
  description?: string;
  project?: string;
  protection?: Protection;
  owner_type?: OwnerType;
  owner_id?: string;
  is_auto_load?: boolean;
  source_type?: SourceType;
  source_url?: string;
  file_path?: string;
  file_permissions?: string;
  agent?: string;
  status?: DocumentStatus;
  skill_ref?: string;
  embedding_model_id?: string;
}

// What you pass to update a document's content (triggers re-chunking + re-embedding)
export interface IUpdateDocumentProps {
  id: number;
  content: string;
  agent?: string;
  description?: string;
  status?: DocumentStatus;
  embedding_model_id?: string;
}

// What you pass to update fields without changing content (no re-embedding needed)
export interface IUpdateFieldsProps {
  id: number;
  agent?: string;
  name?: string;
  domain?: Domain;
  document_type?: string;
  project?: string;
  protection?: Protection;
  owner_type?: OwnerType;
  owner_id?: string;
  is_auto_load?: boolean;
  description?: string;
  source_type?: SourceType;
  source_url?: string;
  file_path?: string;
  file_permissions?: string;
  status?: DocumentStatus;
  skill_ref?: string;
  embedding_model_id?: string;
}

// Filters for listing documents
export interface IListDocumentsProps {
  domain?: Domain;
  document_type?: string;
  project?: string;
  limit?: number;
}

// =============================================================================
// Shared interfaces — used across multiple files
// =============================================================================

// Supabase client — structural type covering all methods we use
// Defined here once so every file agrees on the shape
export interface ISupabaseClientProps {
  from: (table: string) => any;
  rpc: (functionName: string, params: Record<string, unknown>) => PromiseLike<{ data: unknown; error: { message: string } | null }>;
}

// OpenAI client — structural type covering embedding generation
export interface IOpenAIClientProps {
  embeddings: { create: (params: { model: string; input: string }) => Promise<{ data: Array<{ embedding: number[] }> }> };
}

// Combined clients — passed to functions that need both database and AI
// cohereApiKey is optional — reranking is skipped when not provided
export interface IClientsProps {
  supabase: ISupabaseClientProps;
  openai: IOpenAIClientProps;
  cohereApiKey?: string;
}
