import { writeFileSync, readFileSync, mkdirSync, existsSync } from 'fs';
import { resolve } from 'path';
import type { LedgerConfig } from '../lib/config.js';
import { fetchPersonaNotes, updateNoteHash } from '../lib/notes.js';
import { contentHash } from '../lib/hash.js';
import { generateClaudeMd, generateMemoryMd } from '../lib/generators.js';

interface PullOptions {
  quiet: boolean;
  force: boolean;
}

export async function pull(config: LedgerConfig, options: PullOptions): Promise<void> {
  const { quiet, force } = options;
  const notes = await fetchPersonaNotes(config.supabase);

  if (notes.length === 0) {
    if (!quiet) console.error('No cached notes found in Ledger.');
    return;
  }

  mkdirSync(config.memoryDir, { recursive: true });

  const writtenFiles: string[] = [];
  const conflicts: string[] = [];

  for (const note of notes) {
    const localFile = note.metadata.local_file as string | undefined;
    if (!localFile) continue;

    const filePath = resolve(config.memoryDir, localFile);
    const ledgerContent = note.content;
    const ledgerHash = contentHash(ledgerContent);
    const storedHash = note.metadata.content_hash as string | undefined;

    if (!force && existsSync(filePath)) {
      const localRaw = readFileSync(filePath, 'utf-8').trim();
      const localHash = contentHash(localRaw);

      // If local content differs from what we last wrote (stored hash), it's been modified
      if (storedHash && localHash !== storedHash) {
        // If Ledger also changed, it's a conflict
        if (ledgerHash !== storedHash) {
          conflicts.push(localFile);
          console.log(`CONFLICT:${localFile}`);
          continue;
        }
        // Only local changed — don't overwrite
        conflicts.push(localFile);
        console.log(`CONFLICT:${localFile}`);
        continue;
      }
    }

    writeFileSync(filePath, `${ledgerContent}\n`, 'utf-8');
    writtenFiles.push(localFile);

    // Store the hash of what we wrote so check can detect local modifications
    if (!storedHash || storedHash !== ledgerHash) {
      await updateNoteHash(config.supabase, note.id, ledgerHash);
    }

    if (!quiet) console.error(`  wrote ${localFile}`);
  }

  writeGeneratedFiles(config, notes, writtenFiles, conflicts, force, quiet);

  if (!quiet) {
    console.error(`\nPull complete: ${writtenFiles.length} written, ${conflicts.length} conflicts`);
  }
}

function writeGeneratedFiles(
  config: LedgerConfig,
  notes: Awaited<ReturnType<typeof fetchPersonaNotes>>,
  writtenFiles: string[],
  conflicts: string[],
  force: boolean,
  quiet: boolean,
): void {
  const allLocalFiles = [...writtenFiles, ...conflicts];

  const memoryPath = resolve(config.memoryDir, 'MEMORY.md');
  writeFileSync(memoryPath, generateMemoryMd(allLocalFiles), 'utf-8');
  if (!quiet) console.error('  wrote MEMORY.md');

  const feedbackNotes = notes.filter(n => (n.metadata.type as string) === 'feedback');
  const newClaudeMd = generateClaudeMd(feedbackNotes);

  // Protect user-authored CLAUDE.md — only overwrite if it was generated by Ledger
  if (existsSync(config.claudeMdPath)) {
    const existing = readFileSync(config.claudeMdPath, 'utf-8');
    if (!existing.startsWith('# Global Rules') && !force) {
      console.log('CONFLICT:CLAUDE.md (exists with non-Ledger content, use --force to overwrite)');
      return;
    }
  }

  writeFileSync(config.claudeMdPath, newClaudeMd, 'utf-8');
  if (!quiet) console.error('  wrote ~/CLAUDE.md');
}
